use_frameworks!

platform :ios, '9.0'

target 'CXTestKit_Example' do
  pod 'CXTestKit', :path => '../'

  target 'CXTestKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
